CREATE TABLE 00_Current(
    Position INT NOT NULL,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Points INT NOT NULL,
    DroppedWeeks INT NOT NULL,
    Club VARCHAR(48) NOT NULL,
    Country VARCHAR(2) NOT NULL,
    iRating INT NOT NULL,
    AvgFinish DECIMAL(4,2) NOT NULL,
    Top5s INT NOT NULL,
    Starts INT NOT NULL,
    LapsLed INT NOT NULL,
    Wins INT NOT NULL,
    Incidents INT NOT NULL,
    Division INT NOT NULL,
    WeeksCounted INT NOT NULL,
    LapsCompleted INT NOT NULL,
    Poles INT NOT NULL,
    AvgStart DECIMAL(4,2) NOT NULL,
    CustomerID INT NOT NULL,
    PRIMARY KEY (CustomerID)
);

CREATE TABLE 01_Daytona(
    Position INT NOT NULL,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Points INT NOT NULL,
    DroppedWeeks INT NOT NULL,
    Club VARCHAR(48) NOT NULL,
    Country VARCHAR(2) NOT NULL,
    iRating INT NOT NULL,
    AvgFinish DECIMAL(4,2) NOT NULL,
    Top5s INT NOT NULL,
    Starts INT NOT NULL,
    LapsLed INT NOT NULL,
    Wins INT NOT NULL,
    Incidents INT NOT NULL,
    Division INT NOT NULL,
    WeeksCounted INT NOT NULL,
    LapsCompleted INT NOT NULL,
    Poles INT NOT NULL,
    AvgStart DECIMAL(4,2) NOT NULL,
    CustomerID INT NOT NULL,
    PRIMARY KEY (CustomerID)
);

CREATE TABLE 02_Rockingham(
    Position INT NOT NULL,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Points INT NOT NULL,
    DroppedWeeks INT NOT NULL,
    Club VARCHAR(48) NOT NULL,
    Country VARCHAR(2) NOT NULL,
    iRating INT NOT NULL,
    AvgFinish DECIMAL(4,2) NOT NULL,
    Top5s INT NOT NULL,
    Starts INT NOT NULL,
    LapsLed INT NOT NULL,
    Wins INT NOT NULL,
    Incidents INT NOT NULL,
    Division INT NOT NULL,
    WeeksCounted INT NOT NULL,
    LapsCompleted INT NOT NULL,
    Poles INT NOT NULL,
    AvgStart DECIMAL(4,2) NOT NULL,
    CustomerID INT NOT NULL,
    PRIMARY KEY (CustomerID)
);

CREATE TABLE 03_Homestead(
    Position INT NOT NULL,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Points INT NOT NULL,
    DroppedWeeks INT NOT NULL,
    Club VARCHAR(48) NOT NULL,
    Country VARCHAR(2) NOT NULL,
    iRating INT NOT NULL,
    AvgFinish DECIMAL(4,2) NOT NULL,
    Top5s INT NOT NULL,
    Starts INT NOT NULL,
    LapsLed INT NOT NULL,
    Wins INT NOT NULL,
    Incidents INT NOT NULL,
    Division INT NOT NULL,
    WeeksCounted INT NOT NULL,
    LapsCompleted INT NOT NULL,
    Poles INT NOT NULL,
    AvgStart DECIMAL(4,2) NOT NULL,
    CustomerID INT NOT NULL,
    PRIMARY KEY (CustomerID)
);

CREATE TABLE 04_Atlanta(
    Position INT NOT NULL,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Points INT NOT NULL,
    DroppedWeeks INT NOT NULL,
    Club VARCHAR(48) NOT NULL,
    Country VARCHAR(2) NOT NULL,
    iRating INT NOT NULL,
    AvgFinish DECIMAL(4,2) NOT NULL,
    Top5s INT NOT NULL,
    Starts INT NOT NULL,
    LapsLed INT NOT NULL,
    Wins INT NOT NULL,
    Incidents INT NOT NULL,
    Division INT NOT NULL,
    WeeksCounted INT NOT NULL,
    LapsCompleted INT NOT NULL,
    Poles INT NOT NULL,
    AvgStart DECIMAL(4,2) NOT NULL,
    CustomerID INT NOT NULL,
    PRIMARY KEY (CustomerID)
);

CREATE TABLE 05_CharlotteRoval(
    Position INT NOT NULL,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Points INT NOT NULL,
    DroppedWeeks INT NOT NULL,
    Club VARCHAR(48) NOT NULL,
    Country VARCHAR(2) NOT NULL,
    iRating INT NOT NULL,
    AvgFinish DECIMAL(4,2) NOT NULL,
    Top5s INT NOT NULL,
    Starts INT NOT NULL,
    LapsLed INT NOT NULL,
    Wins INT NOT NULL,
    Incidents INT NOT NULL,
    Division INT NOT NULL,
    WeeksCounted INT NOT NULL,
    LapsCompleted INT NOT NULL,
    Poles INT NOT NULL,
    AvgStart DECIMAL(4,2) NOT NULL,
    CustomerID INT NOT NULL,
    PRIMARY KEY (CustomerID)
);

CREATE TABLE 06_Michigan(
    Position INT NOT NULL,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Points INT NOT NULL,
    DroppedWeeks INT NOT NULL,
    Club VARCHAR(48) NOT NULL,
    Country VARCHAR(2) NOT NULL,
    iRating INT NOT NULL,
    AvgFinish DECIMAL(4,2) NOT NULL,
    Top5s INT NOT NULL,
    Starts INT NOT NULL,
    LapsLed INT NOT NULL,
    Wins INT NOT NULL,
    Incidents INT NOT NULL,
    Division INT NOT NULL,
    WeeksCounted INT NOT NULL,
    LapsCompleted INT NOT NULL,
    Poles INT NOT NULL,
    AvgStart DECIMAL(4,2) NOT NULL,
    CustomerID INT NOT NULL,
    PRIMARY KEY (CustomerID)
);

CREATE TABLE 07_Richmond(
    Position INT NOT NULL,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Points INT NOT NULL,
    DroppedWeeks INT NOT NULL,
    Club VARCHAR(48) NOT NULL,
    Country VARCHAR(2) NOT NULL,
    iRating INT NOT NULL,
    AvgFinish DECIMAL(4,2) NOT NULL,
    Top5s INT NOT NULL,
    Starts INT NOT NULL,
    LapsLed INT NOT NULL,
    Wins INT NOT NULL,
    Incidents INT NOT NULL,
    Division INT NOT NULL,
    WeeksCounted INT NOT NULL,
    LapsCompleted INT NOT NULL,
    Poles INT NOT NULL,
    AvgStart DECIMAL(4,2) NOT NULL,
    CustomerID INT NOT NULL,
    PRIMARY KEY (CustomerID)
);

CREATE TABLE 08_Darlington(
    Position INT NOT NULL,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Points INT NOT NULL,
    DroppedWeeks INT NOT NULL,
    Club VARCHAR(48) NOT NULL,
    Country VARCHAR(2) NOT NULL,
    iRating INT NOT NULL,
    AvgFinish DECIMAL(4,2) NOT NULL,
    Top5s INT NOT NULL,
    Starts INT NOT NULL,
    LapsLed INT NOT NULL,
    Wins INT NOT NULL,
    Incidents INT NOT NULL,
    Division INT NOT NULL,
    WeeksCounted INT NOT NULL,
    LapsCompleted INT NOT NULL,
    Poles INT NOT NULL,
    AvgStart DECIMAL(4,2) NOT NULL,
    CustomerID INT NOT NULL,
    PRIMARY KEY (CustomerID)
);

CREATE TABLE 09_Dover(
    Position INT NOT NULL,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Points INT NOT NULL,
    DroppedWeeks INT NOT NULL,
    Club VARCHAR(48) NOT NULL,
    Country VARCHAR(2) NOT NULL,
    iRating INT NOT NULL,
    AvgFinish DECIMAL(4,2) NOT NULL,
    Top5s INT NOT NULL,
    Starts INT NOT NULL,
    LapsLed INT NOT NULL,
    Wins INT NOT NULL,
    Incidents INT NOT NULL,
    Division INT NOT NULL,
    WeeksCounted INT NOT NULL,
    LapsCompleted INT NOT NULL,
    Poles INT NOT NULL,
    AvgStart DECIMAL(4,2) NOT NULL,
    CustomerID INT NOT NULL,
    PRIMARY KEY (CustomerID)
);

CREATE TABLE 10_LasVegas(
    Position INT NOT NULL,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Points INT NOT NULL,
    DroppedWeeks INT NOT NULL,
    Club VARCHAR(48) NOT NULL,
    Country VARCHAR(2) NOT NULL,
    iRating INT NOT NULL,
    AvgFinish DECIMAL(4,2) NOT NULL,
    Top5s INT NOT NULL,
    Starts INT NOT NULL,
    LapsLed INT NOT NULL,
    Wins INT NOT NULL,
    Incidents INT NOT NULL,
    Division INT NOT NULL,
    WeeksCounted INT NOT NULL,
    LapsCompleted INT NOT NULL,
    Poles INT NOT NULL,
    AvgStart DECIMAL(4,2) NOT NULL,
    CustomerID INT NOT NULL,
    PRIMARY KEY (CustomerID)
);

CREATE TABLE 11_CanadianTire(
    Position INT NOT NULL,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Points INT NOT NULL,
    DroppedWeeks INT NOT NULL,
    Club VARCHAR(48) NOT NULL,
    Country VARCHAR(2) NOT NULL,
    iRating INT NOT NULL,
    AvgFinish DECIMAL(4,2) NOT NULL,
    Top5s INT NOT NULL,
    Starts INT NOT NULL,
    LapsLed INT NOT NULL,
    Wins INT NOT NULL,
    Incidents INT NOT NULL,
    Division INT NOT NULL,
    WeeksCounted INT NOT NULL,
    LapsCompleted INT NOT NULL,
    Poles INT NOT NULL,
    AvgStart DECIMAL(4,2) NOT NULL,
    CustomerID INT NOT NULL,
    PRIMARY KEY (CustomerID)
);

CREATE TABLE 12_Texas(
    Position INT NOT NULL,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Points INT NOT NULL,
    DroppedWeeks INT NOT NULL,
    Club VARCHAR(48) NOT NULL,
    Country VARCHAR(2) NOT NULL,
    iRating INT NOT NULL,
    AvgFinish DECIMAL(4,2) NOT NULL,
    Top5s INT NOT NULL,
    Starts INT NOT NULL,
    LapsLed INT NOT NULL,
    Wins INT NOT NULL,
    Incidents INT NOT NULL,
    Division INT NOT NULL,
    WeeksCounted INT NOT NULL,
    LapsCompleted INT NOT NULL,
    Poles INT NOT NULL,
    AvgStart DECIMAL(4,2) NOT NULL,
    CustomerID INT NOT NULL,
    PRIMARY KEY (CustomerID)
);

CREATE TABLE 13_Martinsville(
    Position INT NOT NULL,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Points INT NOT NULL,
    DroppedWeeks INT NOT NULL,
    Club VARCHAR(48) NOT NULL,
    Country VARCHAR(2) NOT NULL,
    iRating INT NOT NULL,
    AvgFinish DECIMAL(4,2) NOT NULL,
    Top5s INT NOT NULL,
    Starts INT NOT NULL,
    LapsLed INT NOT NULL,
    Wins INT NOT NULL,
    Incidents INT NOT NULL,
    Division INT NOT NULL,
    WeeksCounted INT NOT NULL,
    LapsCompleted INT NOT NULL,
    Poles INT NOT NULL,
    AvgStart DECIMAL(4,2) NOT NULL,
    CustomerID INT NOT NULL,
    PRIMARY KEY (CustomerID)
);

CREATE TABLE 14_Phoenix(
    Position INT NOT NULL,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Points INT NOT NULL,
    DroppedWeeks INT NOT NULL,
    Club VARCHAR(48) NOT NULL,
    Country VARCHAR(2) NOT NULL,
    iRating INT NOT NULL,
    AvgFinish DECIMAL(4,2) NOT NULL,
    Top5s INT NOT NULL,
    Starts INT NOT NULL,
    LapsLed INT NOT NULL,
    Wins INT NOT NULL,
    Incidents INT NOT NULL,
    Division INT NOT NULL,
    WeeksCounted INT NOT NULL,
    LapsCompleted INT NOT NULL,
    Poles INT NOT NULL,
    AvgStart DECIMAL(4,2) NOT NULL,
    CustomerID INT NOT NULL,
    PRIMARY KEY (CustomerID)
);
